website/auth.py
import csv
from flask_login import current_user
from sentence_transformers import util,SentenceTransformer
from io import TextIOWrapper
import time
import jwt
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, flash, session, redirect, url_for
from .models import TestResultData, User,TestResult,TopicResult
from . import mongo2
from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app
import openai


auth = Blueprint('auth', __name__)

def get_random_questions(num_questions,sub):
    if(sub=='java'):

        questions = mongo2.db.java.aggregate([
            { '$sample': { 'size': num_questions } },
            { '$project': { '_id': 0, 'Question': 1 } }
        ])
        return list(questions)
    else:
        questions = mongo2.db.python.aggregate([
            { '$sample': { 'size': num_questions } },
            { '$project': { '_id': 0, 'Question': 1 } }
        ])
        return list(questions)



@auth.route('/java')
def java():
    num_questions = 10  # Specify the number of questions needed
    questions = get_random_questions(num_questions,sub='java')
    
    return render_template('java.html', questions=questions,num_questions=num_questions)

@auth.route('/python')
def python():
    num_questions = 10  # Specify the number of questions needed
    questions = get_random_questions(num_questions,sub='python')
    
    return render_template('python.html', questions=questions,num_questions=num_questions)

@auth.route('/')
def home():
    token = session.get('token')
    if token:
        try:
            payload = jwt.decode(token, current_app.config['SECRET_KEY'], algorithms=['HS256'])
            user_id = payload['user_id']
            user = User.objects(id=user_id).first()
            if user:
                last_activity = session.get('last_activity')
                if last_activity and time.time() - last_activity > 24 * 60 * 60:  # one day of inactivity
                    session.pop('token', None)  # Remove the token from the session
                    flash('Session expired. Please log in again.')
                    return redirect(url_for('auth.login'))
                return render_template("userdash.html", user=user)
            else:
                flash('Invalid token')
        except jwt.ExpiredSignatureError:
            flash('Token expired')
            return redirect(url_for('auth.logout'))
        except jwt.InvalidTokenError:
            flash('Invalid token')
            return redirect(url_for('auth.logout'))

    return redirect(url_for('auth.login'))


@auth.route("/uploadpage")
def uploadpage():
    return render_template("upload.html")


ALLOWED_EXTENSIONS = {'csv'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@auth.route('/upload', methods=['GET', 'POST'])
def upload():
    uploaded_count = 0
    skipped_count = 0

    if request.method == 'POST':
        subject = request.form.get('subject')
        csv_file = request.files.get('csv_file')

        if csv_file and allowed_file(csv_file.filename):
            
            csv_data = TextIOWrapper(csv_file, encoding='utf-8')
            reader = csv.DictReader(csv_data)

            for row in reader:
                Question = row.get('Question')
                if not Question:
                    skipped_count += 1
                    continue  
                existing_record = mongo2.db[subject].find_one({'Question': Question})
                if existing_record is not None:
                    skipped_count += 1
                    continue 

                else:
                    mongo2.db[subject].insert_one(row)
                    uploaded_count += 1

    return render_template('upload.html', uploaded_count=uploaded_count, skipped_count=skipped_count)



@auth.route('/evaluate', methods=['POST'])
def evaluate_answers():
    token = session.get('token')
    payload = jwt.decode(token, current_app.config['SECRET_KEY'], algorithms=['HS256'])
    user_id = payload['user_id']
    user = User.objects(id=user_id).first()
    model_name = 'paraphrase-MiniLM-L6-v2'
    sentence_transformer = SentenceTransformer(model_name)
    subject = request.form.get('subject')
    user_answers = request.form.getlist('answer')
    questions = request.form.getlist('question')

    difficulty_dict = {}
    question_answers = {}
    question_topic={}

    for question in questions:
        doc = mongo2.db[subject].find_one({'Question': question})
        topic=doc['\ufeffTopic']
        difficulty = doc['Difficulty']
        answer = doc['Answer']
        difficulty_dict[question] = difficulty
        question_answers[question] = answer
        question_topic[question]=topic
          
    # Pre-encode sentence embeddings for all answers
    answer_embeddings = sentence_transformer.encode(list(question_answers.values()))

    difficulty_counts = {'Easy': {'Right': 0, 'Wrong': 0}, 'Medium': {'Right': 0, 'Wrong': 0}, 'Hard': {'Right': 0, 'Wrong': 0}}
    results = []
    correct = 0
 
    easy_topics = []
    medium_topics = []
    hard_topics = []
    for question, user_answer, answer_embedding in zip(questions, user_answers, answer_embeddings):
        difficulty = difficulty_dict[question]
        actual_embedding = answer_embedding

        user_embedding = sentence_transformer.encode([user_answer])[0]

        similarity = util.cos_sim(user_embedding, actual_embedding)
        percentage = float(similarity * 100)

        if percentage >= 70:
            correctness = 'Right'
            correct += 1
            difficulty_counts[difficulty]['Right'] += 1

            # Update counts for topics
            topic = question_topic[question]
        if percentage >= 70:
            correctness = 'Right'
            correct += 1
            difficulty_counts[difficulty]['Right'] += 1

            # Update counts for topics
            topic = question_topic[question]
            if difficulty == 'Easy':
                update_topic_counts(easy_topics, topic, True)
            elif difficulty == 'Medium':
                update_topic_counts(medium_topics, topic, True)
            elif difficulty == 'Hard':
                update_topic_counts(hard_topics, topic, True)
        else:
            correctness = 'Wrong'
            difficulty_counts[difficulty]['Wrong'] += 1

            # Update counts for topics
            topic = question_topic[question]
            if difficulty == 'Easy':
                update_topic_counts(easy_topics, topic, False)
            elif difficulty == 'Medium':
                update_topic_counts(medium_topics, topic, False)
            elif difficulty == 'Hard':
                update_topic_counts(hard_topics, topic, False)

        result = {
            'question': question,
            'correctness': correctness
        }
        results.append(result)

    total_questions = len(questions)
    correct_easy_questions = sum(1 for r in results if r['correctness'] == 'Right' and difficulty_dict[r['question']] == 'Easy')
    correct_medium_questions = sum(1 for r in results if r['correctness'] == 'Right' and difficulty_dict[r['question']] == 'Medium')
    correct_hard_questions = sum(1 for r in results if r['correctness'] == 'Right' and difficulty_dict[r['question']] == 'Hard')

    total_easy_questions = sum(1 for difficulty in difficulty_dict.values() if difficulty == 'Easy')
    total_medium_questions = sum(1 for difficulty in difficulty_dict.values() if difficulty == 'Medium')
    total_hard_questions = sum(1 for difficulty in difficulty_dict.values() if difficulty == 'Hard')
    
        # Create a new test result object
    save_test_result(user.email, subject, correct, total_questions,
                     total_easy_questions, total_medium_questions, total_hard_questions,
                     correct_easy_questions, correct_medium_questions, correct_hard_questions,
                     easy_topics, medium_topics, hard_topics)
    return render_template('evaluate.html', correct=correct, total_questions=total_questions,
                           total_easy_questions=total_easy_questions, total_medium_questions=total_medium_questions,
                           total_hard_questions=total_hard_questions, correct_easy_questions=correct_easy_questions,
                           correct_medium_questions=correct_medium_questions,
                           correct_hard_questions=correct_hard_questions)



def update_topic_counts(topic_results, topic, is_correct):
    # Access the list within the ListField object
    topic_results_list = topic_results if isinstance(topic_results, list) else []

    # Check if the topic already exists in the list
    for topic_result in topic_results_list:
        if topic_result.topic == topic:
            if is_correct:
                topic_result.correct_answers += 1
            topic_result.number_of_questions += 1
            return

    # If the topic doesn't exist, create a new topic result object
    topic_result = TopicResult(topic=topic, correct_answers=1 if is_correct else 0, number_of_questions=1)
    topic_results_list.append(topic_result)

    # Save the updated list back to the ListField object if necessary
    if not isinstance(topic_results, list):
        topic_results = topic_results_list

    



def save_test_result(email, subject, correct, total_questions,
                     total_easy_questions, total_medium_questions, total_hard_questions,
                     correct_easy_questions, correct_medium_questions, correct_hard_questions,
                     easy_topics, medium_topics, hard_topics):

website/templates/answer.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='qna.css') }}">
{% endblock %}
{% block title %}Ans page{% endblock %}
{% block context %}
<h1>Hi</h1>
<h1>Here is answer to your Query: </h1>
<p>{{ response }}</p>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='header.css')}}">
{% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <h4 class="nav-button1" >AIAS</h4>
            {% if session.token %}
            <a class="nav-button1" href="/">HOME</a>
            <a class="nav-button2" href="/ask">ASK A QUERY</a>
            <a class="nav-button4" href="/result">RESULT</a>
            <a class="nav-button3" href="/logout">LOGOUT</a>
            {% endif %}
        </nav>     
    </header>
    {% with messages=get_flashed_messages() %}
        {% if messages %}
            {% for msg in messages %}
                <div class="alert">
                    <p>{{msg}}</p>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block context %}{% endblock %}
</body>
<script>
const alerts = document.querySelectorAll('.alert');

alerts.forEach(function(alert) {
    setTimeout(function() {
        alert.style.display = 'none';
    }, 3000);
});
</script>
</html>

website/templates/evaluate.html
{% extends "base.html" %}
{% block title %}Evaluation {% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='evaluate.css') }}">
{% endblock %}

{% block context %}
<div class="result-container">
  <h1>Quiz Result</h1>
  <p class="result-info">Total Questions: {{total_questions}}</p>
  <p class="result-info">Correct Answers: {{correct}}</p>
  <div class="result-section">
    <div class="result-category result-easy">
      <h2>Easy Questions</h2>
      <p class="result-subinfo">Correct: {{correct_easy_questions}}</p>
      <p class="result-subinfo">Wrong: {{total_easy_questions - correct_easy_questions}}</p>
    </div>
    <div class="result-category result-medium">
      <h2>Medium Questions</h2>
      <p class="result-subinfo">Correct: {{correct_medium_questions}}</p>
      <p class="result-subinfo">Wrong: {{total_medium_questions - correct_medium_questions}}</p>
    </div>
    <div class="result-category result-hard">
      <h2>Hard Questions</h2>
      <p class="result-subinfo">Correct: {{correct_hard_questions}}</p>
      <p class="result-subinfo">Wrong: {{total_hard_questions - correct_hard_questions}}</p>
    </div>
  </div>
</div>
{% endblock %}

website/templates/java.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='java.css') }}">
{% endblock %}

{% block title %}Java Test{% endblock %}

{% block context %}
<div class="container">
  <div class="row">
    <div class="col-md-12" align="center">
      <h1>Java Test</h1>
      <form method="post" action="/evaluate">
        {% set last_index = questions|length %}
        {% for question in questions %}
        <div class="question-box" >
          <div>
          <p>{{ loop.index }}Q. {{ question['Question'] }}</p>
          <input type="hidden" name="question" value="{{ question['Question'] }}">
          <input type="hidden" name="subject" value="java">
          <br/><br/>
          <textarea id="answer{{ loop.index }}" name="answer" class="answer-textarea" rows="4" cols="50"></textarea>
          </div>
          <div class = "Buttons_for_voice">
          <button type="button" class="btn btn-primary start-button" onclick="startSpeechRecognition({{ loop.index }})">Start Answering 🎤</button>
          <button type="button" class="btn btn-secondary start-button" onclick="stopSpeechRecognition()">Stop Answering 🎤</button>
          <!--<button type="button" class="btn btn-secondary reset-button" onclick="resetAnswer({{ loop.index }})">Reset</button>-->
          </div>
        </div>
        {% endfor %}

        <div class="navigation-buttons">
          <button type="button" class="button-73" onclick="previousQuestion()">Previous</button>
          <br/><br/>
          <button type="button" class="button-73" onclick="nextQuestion()">Next</button>

          <br/><br/>
          <button id="submit-button" type="submit" class="btn btn-primary button-90">Submit</button>
        </div>

      </form>
    </div>
  </div>
</div>


<script>


var recognition;

function startSpeechRecognition(questionIndex) {
  var answerTextarea = document.getElementById('answer' + questionIndex);
  answerTextarea.value = '';
  answerTextarea.classList.remove('error'); // Remove error class

  if (!recognition || recognition.status === 'inactive') {
    recognition = new webkitSpeechRecognition();
    recognition.continuous = true;

    recognition.onresult = function(event) {
      var transcript = event.results[event.results.length - 1][0].transcript;
      answerTextarea.value += transcript;
    };

    recognition.start();
  }
}

function stopSpeechRecognition() {
  if (recognition) {
    recognition.stop();
    recognition = null;
  }
}

function resetAnswer(questionIndex) {
  var answerTextarea = document.getElementById('answer' + questionIndex);
  answerTextarea.value = '';
  answerTextarea.classList.remove('error'); // Remove error class
}


function validateForm() {
  var answerTextareas = document.getElementsByClassName('answer-textarea');
  var errorCount = 0;

  for (var i = 0; i < answerTextareas.length; i++) {
    var answerTextarea = answerTextareas[i];
    if (answerTextarea.value.trim() === '') {
      answerTextarea.classList.add('error'); // Add error class
      errorCount++;
    }
  }

  if (errorCount > 0) {
    alert('Please answer all questions before submitting.');
    return false;
  }

  return true;
}

var currentQuestion = 0;
var numQuestions = 10;

function showQuestion(questionIndex) {
  var questions = document.getElementsByClassName('question-box');
  for (var i = 0; i < questions.length; i++) {
    questions[i].style.display = 'none';
  }

  questions[questionIndex].style.display = 'block';
  var submitButton = document.getElementById('submit-button');
  if (questionIndex === numQuestions - 1) {
    submitButton.style.display = 'inline-block';
  } else {
    submitButton.style.display = 'none';
  }
}




function nextQuestion() {
  if (currentQuestion < numQuestions - 1) {
    currentQuestion++;
    showQuestion(currentQuestion);
  }
}

function previousQuestion() {
  if (currentQuestion > 0) {
    currentQuestion--;
    showQuestion(currentQuestion);
  }
}

// Show the first question initially
showQuestion(currentQuestion);

  </script>
  
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}">
{% endblock %}

{% block title %}Login Page{% endblock %}

{% block context %}
  <div class="container">
    <form class="login-form"  method="POST">
      <h2>Login</h2>
      <p>To continue your learning jouney 👨‍🏫👨‍🏫👨‍🏫</p>
      <input type="email" placeholder="Email" name="email" required>
      <div class="password-container">
        <input type="password" placeholder="Password" name="password" required>
        <button type="button" class="show-password">Show</button>
      </div>
      <button type="submit">Login</button>
      <p>Don't have an Account? <a href="/signup">Sign Up</a></p>
    </form>
  </div>
  <script>
    const showPasswordButtons = document.querySelectorAll('.show-password');
  
    showPasswordButtons.forEach(function (button) {
      button.addEventListener('click', function () {
        const passwordInput = button.previousElementSibling;
        const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordInput.setAttribute('type', type);
        button.textContent = type === 'password' ? 'Show' : 'Hide';
      });
    });
  </script>
{% endblock %}

website/templates/profile.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">
<style>
  /* Additional styles specific to this page */
  .profile-details {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    margin-top: 20px;
  }

  .profile-row {
    display: flex;
    align-items: center;
    margin-bottom: 10px;
  }

  .profile-label {
    font-size: 18px;
    font-weight: bold;
    margin-right: 10px;
  }

  .profile-value {
    font-size: 18px;
    color: #777;
  }
</style>
{% endblock %}
{% block title %}Profile{% endblock %}
{% block context %}
<div class="detail-container">
  <div class="detail-card">
    <img class="avatar" src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="Avatar">
    <div class="detail-card-content">
      <div class="profile-details">
        <div class="profile-row">
          <span class="profile-label">Name:</span>
          <span class="profile-value">{{ user.first_name }}</span>
        </div>
    <!-- <div class="profile-row">
          <span class="profile-label">Name :</span>
          <span class="profile-value">{{ user.first_name }}</span>
        </div>
          <div class="profile-row">
          <span class="profile-label">Role:</span>
          <span class="profile-value">{{ user.role }}</span>
        </div>
      </div>-->
    </div>
  </div>
</div>
{% endblock %}


website/templates/python.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='java.css') }}">
{% endblock %}

{% block title %}Python Test{% endblock %}

{% block context %}
<div class="container">
  <div class="row">
    <div class="col-md-12" align="center">
      <h1>Python Test</h1>
      <form method="post" action="/evaluate">
        {% set last_index = questions|length %}
        {% for question in questions %}
        <div class="question-box" >
          <div>
          <p>{{ loop.index }}Q. {{ question['Question'] }}</p>
          <input type="hidden" name="question" value="{{ question['Question'] }}">
          <input type="hidden" name="subject" value="Python">
          <br/><br/>
          <textarea id="answer{{ loop.index }}" name="answer" class="answer-textarea" rows="4" cols="50"></textarea>
          </div>
          <div class = "Buttons_for_voice">
          <button type="button" class="btn btn-primary start-button" onclick="startSpeechRecognition({{ loop.index }})">Start Answering 🎤</button>
          <button type="button" class="btn btn-secondary start-button" onclick="stopSpeechRecognition()">Stop Answering 🎤</button>
          <!--<button type="button" class="btn btn-secondary reset-button" onclick="resetAnswer({{ loop.index }})">Reset</button>-->
          </div>
        </div>
        {% endfor %}

        <div class="navigation-buttons">
          <button type="button" class="button-73" onclick="previousQuestion()">Previous</button>
          <br/><br/>
          <button type="button" class="button-73" onclick="nextQuestion()">Next</button>

          <br/><br/>
          <button id="submit-button" type="submit" class="btn btn-primary button-90">Submit</button>
        </div>

      </form>
    </div>
  </div>
</div>


<script>


var recognition;

function startSpeechRecognition(questionIndex) {
  var answerTextarea = document.getElementById('answer' + questionIndex);
  answerTextarea.value = '';
  answerTextarea.classList.remove('error'); // Remove error class

  if (!recognition || recognition.status === 'inactive') {
    recognition = new webkitSpeechRecognition();
    recognition.continuous = true;

    recognition.onresult = function(event) {
      var transcript = event.results[event.results.length - 1][0].transcript;
      answerTextarea.value += transcript;
    };

    recognition.start();
  }
}

function stopSpeechRecognition() {
  if (recognition) {
    recognition.stop();
    recognition = null;
  }
}

function resetAnswer(questionIndex) {
  var answerTextarea = document.getElementById('answer' + questionIndex);
  answerTextarea.value = '';
  answerTextarea.classList.remove('error'); // Remove error class
}


function validateForm() {
  var answerTextareas = document.getElementsByClassName('answer-textarea');
  var errorCount = 0;

  for (var i = 0; i < answerTextareas.length; i++) {
    var answerTextarea = answerTextareas[i];
    if (answerTextarea.value.trim() === '') {
      answerTextarea.classList.add('error'); // Add error class
      errorCount++;
    }
  }

  if (errorCount > 0) {
    alert('Please answer all questions before submitting.');
    return false;
  }

  return true;
}

var currentQuestion = 0;
var numQuestions = 10;

function showQuestion(questionIndex) {
  var questions = document.getElementsByClassName('question-box');
  for (var i = 0; i < questions.length; i++) {
    questions[i].style.display = 'none';
  }

  questions[questionIndex].style.display = 'block';
  var submitButton = document.getElementById('submit-button');
  if (questionIndex === numQuestions - 1) {
    submitButton.style.display = 'inline-block';
  } else {
    submitButton.style.display = 'none';
  }
}




function nextQuestion() {
  if (currentQuestion < numQuestions - 1) {
    currentQuestion++;
    showQuestion(currentQuestion);
  }
}

function previousQuestion() {
  if (currentQuestion > 0) {
    currentQuestion--;
    showQuestion(currentQuestion);
  }
}

// Show the first question initially
showQuestion(currentQuestion);

  </script>
  
{% endblock %}

website/templates/result.html
{% extends 'base.html' %}
{% block title %}Result page{% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='result.css') }}">
<style>
  .details-table {
    display: none;
  }
</style>
<script>
  function toggleDetails(index) {
    var detailsTable = document.getElementById("details-table-" + index);
    var button = document.getElementById("toggle-button-" + index);
    if (detailsTable.style.display === "none") {
      detailsTable.style.display = "table";
      button.innerHTML = "Hide Details";
    } else {
      detailsTable.style.display = "none";
      button.innerHTML = "Show Details";
    }
  }
</script>
{% endblock %}
{% block context %}
  <div class="result-table">
    <table>
      <thead>
        <tr>
          <th>Subject</th>
          <th>Easy</th>
          <th>Medium</th>
          <th>Hard</th>
          <th>Date</th>
          <th>Time</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for result in test_results %}
          <tr>
            <td>{{ result.subject }}</td>
            <td>{{ result.correct_easy_questions }}/{{ result.total_easy_questions }}</td>
            <td>{{ result.correct_medium_questions }}/{{ result.total_medium_questions }}</td>
            <td>{{ result.correct_hard_questions }}/{{ result.total_hard_questions }}</td>
            <td>{{ result.date }}</td>
            <td>{{ result.time }}</td>
            <td>
              <button id="toggle-button-{{ loop.index0 }}" onclick="toggleDetails({{ loop.index0 }})">Show Details</button>
            </td>
          </tr>
          <tr class="details-table" id="details-table-{{ loop.index0 }}">
            <td colspan="6">
              <table>
                <caption>Easy Topics</caption>
                <thead>
                  <tr>
                    <th>Topic</th>
                    <th>Correct Answers</th>
                    <th>Number of Questions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for topic in result.easy_topics %}
                    <tr>
                      <td>{{ topic.topic }}</td>
                      <td>{{ topic.correct_answers }}</td>
                      <td>{{ topic.number_of_questions }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </td>
            <td>
              <table>
                <caption>Medium Topics</caption>
                <thead>
                  <tr>
                    <th>Topic</th>
                    <th>Correct Answers</th>
                    <th>Number of Questions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for topic in result.medium_topics %}
                    <tr>
                      <td>{{ topic.topic }}</td>
                      <td>{{ topic.correct_answers }}</td>
                      <td>{{ topic.number_of_questions }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </td>
            <td>
              <table>
                <caption>Hard Topics</caption>
                <thead>
                  <tr>
                    <th>Topic</th>
                    <th>Correct Answers</th>
                    <th>Number of Questions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for topic in result.hard_topics %}
                    <tr>
                      <td>{{ topic.topic }}</td>
                      <td>{{ topic.correct_answers }}</td>
                      <td>{{ topic.number_of_questions }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

website/templates/takeq.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='qna.css') }}">
{% endblock %}
{% block title %}Ask page{% endblock %}
{% block context %}
<h1>Ask a queryy</h1>
<br/><br/>
<form action="/ans" method="POST">
    <textarea name="query"></textarea>
    <button type="submit">Submit</button>
</form>

{% endblock %}

website/templates/upload.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">
{% endblock %}
{% block title %}
The admin page
{% endblock %}
{% block context %}

<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="upload-form">
          <h4>Upload CSV File</h4>
          <form method="POST" action="{{ url_for('auth.upload') }}" enctype="multipart/form-data">
            <div class="form-group">
              <label for="subject">Subject:</label>
              <select class="form-control" id="subject" name="subject" >
                <option value="select">select</option>
                <option value="java">java</option>
                <option value="python">python</option>
              </select>
            </div>
            <div class="form-group">
              <label for="csv_file">CSV File:</label>
              <input type="file" class="form-control-file" id="csv_file" name="csv_file">
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
          </form>
          {% if uploaded_count or skipped_count %}
          <div class="upload-results">
            <p>{{ uploaded_count }} records uploaded successfully.</p>
            <p>{{ skipped_count }} records skipped (already exist).</p>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

website/templates/userdash.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">
{% endblock %}

{% block title %}User Dashboard{% endblock %}


{% block context %}
{% if user.role == 'student' %}
<div class="container">
    <div class="subject-box">
      <img class="box-icon" src="https://cdn-icons-png.flaticon.com/512/5968/5968282.png" alt="Java Icon">
       <h1>Java</h1>
        <a class="button" href="/java">Attempt</a>
    </div>
    <div class="subject-box1">
      <img class="box-icon" src="https://cdn-icons-png.flaticon.com/512/5968/5968350.png" alt="Java Icon">
       <h1>Python</h1>
        <a class="button" href="/python">Attempt</a>
    </div>
    <!--<div class="right-box">
      <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
      <p class="chat">Have a Query?</p>
        <a class="button-10" href="/ask">Ask us</a>
    </div>-->
</div>

{% else %}  
<h2>You Can Upload Questions Here</h2>
<a class="button" href="/uploadpage">Upload</a>
{% endif %}
{% endblock %}